module ImdLatte where

import AbsLatte

-- Haskell module generated by the BNF converter

data Register = Reg Integer | Mem Integer

data Block = Ident [Quadruple]

data Quadruple
    = QAdd Register Register Register
    | QSub Register Register Register
    | QMul Register Register Register
    | QDiv Register Register Register
    | QAss Register Register Register
    | QInc Register
    | QDec Register
    | QRet
    | QGoTo Ident
    | QNeg Register
    | QAnd Register Register Register
    | QOr Register Register Register
    | QNot Register
    | QRel RelOp Register Register Register
    | Func Ident [Register]
