#!/bin/bash
set -e
if [ -z "$1" ]; then
    echo "Use path to file as an argument!"
    exit
fi

filename=$(basename -- "$1")
filepath_no_extension="${1%.*}"
filename_no_extension="${filename%%.*}"
./lat_to_asm_bin $1;
mv $filepath_no_extension.s programs;
gcc programs/$filename_no_extension.s lib/runtime.o -o programs/$filename_no_extension;
